### ISSUE TITLE
GIven Items are duplicated when several new worlds are spawned during one game run.

### ISSUE THREAD

**Issue by dequbed** [MiraWaNeko/IDTGATT#1]
Java version: OpenJDK 1.8.0_131
Minecraft version: 1.10.2
IDTGATT version: 1.10.2-1.0.0

## Steps to reproduce:
Used config:
```json
{
    "message": true,
    "items": [
        {
            "id": "minecraft:iron_helmet",
            "amount": 1
        }
    ]
}
```

```
1. Create new world
2. Save and return to title
3. Create another new world
4. Save and return
...
```

## Expected behaviour:

In each new world the player should receive one Iron Helmet

## Observed behaviour:

For the first created world one Iron Helmet is given.
For the second however the player is given *two* Iron Helmets
On the third the player is given *three* Iron Helmets.
And so on.

## Further notes:
This seems to be related to the mod loading idtgatt.json on each world creation but not replacing the old config, since when you change the config after the first world creation to the following:
```json
{
    "message": true,
    "items": [
        {
            "id": "minecraft:iron_chestplate",
            "amount": 1
        }
    ]
}
```
The player is then given a helmet *and* a chestplate on the second new world. On a third new world creation the player is then given one helmet and *two* chestplates.

**Comment by MiraWaNeko** [comment]
Fixed in 1.0.1
It's up on CurseForge
